apiVersion: v1
kind: Namespace
metadata:
  name: myspace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: myspace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: myspace
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: myspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi
            
            
            
#NOTE:

#If you specify requests and limit on namespace , you must specify reourcequota on deployment yaml , if you not specify the resourcequota on deplyment , it will through 
#an error like below

#kubectl get deploy --namespace myspace
#NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
#helloworld-deployment   0/3     0            0           2m53s

#kubectl describe rs --namespace myspace 
#Events:
#  Type     Reason        Age               From                   Message
#  ----     ------        ----              ----                   -------
#  Warning  FailedCreate  85s               replicaset-controller  Error creating: pods "helloworld-deployment-7b4f4bd79b-qz4hd" is forbidden: 
#failed quota: compute-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
