apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
        - mountPath: /myvol
          name: myvolume
      volumes:
      - name: myvolume
        awsElasticBlockStore:
          volumeID: # insert AWS EBS volumeID here
       #persistentVolumeClaim:
       #  claimName: volume-claim        #use this if you are not using EBS volume
#https://github.com/vinodkumar501/vnbd-kubernetes-itrack-learning-2022/blob/main/volumes/pvc.yml
#https://github.com/vinodkumar501/kubernetes-course-itrack-repo-Udemy/blob/master/volumes/helloworld-with-volume.yml
