kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: standard
provisioner: kubernetes.io/gce-pd
parameters:
 type: gp2
 zone: us-east-1
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: myclaim
 annotations:
   volume.kubernetes.io/storage-class: "standard"
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
    storage: 2Gi
---
kind: Pod
apiVersion: v1
metadata:
 name: mypod
spec:
 containers:
 - name: myfrontend
   image: nginx
   volumeMounts:
    - mountPath: "/var/www/html"
      name: mypd
 volumes:
 - name: mypd
   persistentVolumeClaim:
     claimName: myclaim
