apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: database
  #type: NodePort
  #default its as clusterIP 
  #db should not expose to external world
