apiVersion: v1
kind: Secret
metadata:
  name: helloworld-secrets
type: Opaque
data:
  username: aGVsbG93b3JsZA==                       #helloworld
  password: cGFzc3dvcmQ=                           #root
  rootPassword: cm9vdHBhc3N3b3Jk                   #rootpassword
  database: aGVsbG93b3JsZA==                         #helloworld       #it create db in mysql as helloworld
